# Generated by Django 5.0.6 on 2024-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/assets/portfolio_images/')),
                ('square_meters', models.IntegerField()),
                ('paragraph', models.TextField()),
                ('paragraph2', models.TextField()),
            ],
            options={
                'verbose_name_plural': '01. Portfolio',
            },
        ),
    ]
