# Generated by Django 4.2.14 on 2024-08-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villawebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
