# Generated by Django 4.2.14 on 2024-08-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villawebapp', '0002_portfolio_paragraph2_ar_portfolio_paragraph2_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='paragraph2_ar',
            new_name='paragraph2_el',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='paragraph_ar',
            new_name='paragraph2_nl',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='title_ar',
            new_name='title_el',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph2_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='paragraph_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
