# Generated by Django 4.2.14 on 2024-08-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villawebapp', '0003_rename_paragraph2_ar_portfolio_paragraph2_el_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='paragraph2_zh',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='paragraph_zh',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title_zh',
        ),
    ]
