# Generated by Django 4.2.14 on 2024-08-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villawebapp', '0004_remove_portfolio_paragraph2_zh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='static/assets/images/rooms/'),
        ),
    ]
